### ISSUE TITLE
Invalid tile placement on game 2

### ISSUE THREAD

**Issue by crepeau** [mirdaki/tiger-zone#3]
Network communication seems to have an issue with placing tiles on concurrent games, will have to look into fix

**Comment by mirdaki** [comment]
Seems that the issue is somewhere in TigerZoneClient with missing the first tile placed. An attempt at a fix was tried, but it is hard coded and still  sometimes causes illegal placement for games 1 or 2.

**Comment by crepeau** [comment]
fixed this bY revamping the client/game handler to manage game communication a little better.
